### ISSUE TITLE
The callback startActivity() exists in module IntentLauncher, but only one callback may be registered to a function in a native module.

### ISSUE THREAD

**Issue by LaloHao** [poberwong/react-native-intent-launcher#4]
I'm on API 17
```js
    "react": "16.0.0",
    "react-native": "0.51.0",
    "react-native-intent-launcher": "^0.1.0",
```

Steps to reproduce:
`yarn add react-native-intent-launcher`
`react-native link react-native-intent-launcher`
`react-native run-android`

Class:
```js
export default class WelcomeScreen extends Component {
  componentDidMount() {
    IntentLauncher.startActivity({
      action: 'android.intent.action.VIEW',
      data: './assets/BigBuckBunny_320x180.mp4'
    });
  }

  render() {
    return (
      <View style={styles.container}>
      </View>
    );
  }
}
```

**Comment by poberwong** [comment]
yeah，I met the problem as well, and u'd better remove `try...catch` of native code in order to remove `promise.reject`. I'll fix it recently.

**Comment by ferdicus** [comment]
Any update on this issue?

**Comment by godness84** [comment]
@LaloHao @ferdicus can you describe bettere what's the problem? I don't catch it. Maybe I can help you

**Comment by ferdicus** [comment]
Sorry, I don't even remember anymore what the issue was for me - feel free to disregard my above comment.

Sorry for any caused inconvenience.

**Comment by poberwong** [comment]
Hahahaha, Interesting !
