### ISSUE TITLE
Error: undefined is not an object

### ISSUE THREAD

**Issue by yasir-netlinks** [poberwong/react-native-intent-launcher#5]
I am using `react native: 0.51.0`. I tried the example provided in a fresh project , but I receive this error once the button pressed:
![screenshot from 2017-12-24 14-28-53](https://user-images.githubusercontent.com/26054956/34325693-caf3af72-e8b6-11e7-8025-b88a800aec69.png)

**Comment by dev-hamid** [comment]
+1

**Comment by vibhavagarwal5** [comment]
+1

**Comment by junyuecao** [comment]
+1

**Comment by poberwong** [comment]
I encounter the problem as well. Maybe it is due to failure of command `react-native link`，u'd better check whether the command run successfully before u run the app and I fixed it with linking the library manually

**Comment by poberwong** [comment]
long time no response, close it
