### ISSUE TITLE
How to use this package to open up another app using it's package name?

### ISSUE THREAD

**Issue by felixis-1** [poberwong/react-native-intent-launcher#7]
How to use this package to open up another app using it's package name?

**Comment by alexayub-luizalabs** [comment]
I trying the same....

**Comment by poberwong** [comment]
```java
if (params.hasKey(ATTR_CLASS_NAME)) {
  ComponentName cn;
  if (params.hasKey(ATTR_PACKAGE_NAME)) {
    cn = new ComponentName(params.getString(ATTR_PACKAGE_NAME), params.getString(ATTR_CLASS_NAME));
  } else {
    cn = new ComponentName(getReactApplicationContext(), params.getString(ATTR_CLASS_NAME));
  }
  intent.setComponent(cn);
}
```
above is some of source code in `react-native-intent-launcher`. 
As you see, you can put className as key into the object like following:
`IntentLauncher.startActivity({className: 'com.example.Main2Activity'})`

**Comment by marcosdemetrio** [comment]
This is not working when trying to open another app using `IntentLauncher.startActivity({className: 'com.example.package2'})`, it's trying to find inside current package. 

'Unable to find explicit activity class { com.example.package1/com.example.package2 }'

**Comment by poberwong** [comment]
@marcosdemetrio OK, I will fix it at the weekend.

**Comment by phips28** [comment]
If you still need to open an app by package name, then you can use my fork:
https://github.com/dvel-Inc/react-native-intent-launcher#usage

**Comment by poberwong** [comment]
I will release new version tonight  because I am located in China.

**Comment by phips28** [comment]
thx, so you can close this issue :)
